// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bidirectional.proto

package com.li.rpc;

public final class BidirectionStream {
  private BidirectionStream() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023Bidirectional.proto\022\ncom.li.rpc\"(\n\tMyR" +
      "equest\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\005\"-\n\nM" +
      "yResponse\022\017\n\007message\030\001 \001(\t\022\016\n\006result\030\002 \001" +
      "(\0032N\n\013Bidirection\022?\n\nManyToMany\022\025.com.li" +
      ".rpc.MyRequest\032\026.com.li.rpc.MyResponse(\001" +
      "0\001B!\n\ncom.li.rpcB\021BidirectionStreamP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_li_rpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_li_rpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_MyRequest_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_com_li_rpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_li_rpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_MyResponse_descriptor,
        new java.lang.String[] { "Message", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
