// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bidirectional.proto

package com.li.rpc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.li.rpc.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int64 result = 2;</code>
   * @return The result.
   */
  long getResult();
}
